/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jeff' at '9/12/14 2:35 PM' with Gradle 2.0
 *
 * @author jeff, @date 9/12/14 2:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
